apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-crawling
  description: Backstage crawling
  annotations:
    github.com/project-slug: smajlovic-info/backstage-crawling
    backstage.io/kubernetes-id: backstage-crawling
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://knauf.com
      title: Knauf.com
      icon: link
spec:
  type: service
  lifecycle: experimental
  owner: group:default/devops
  system: cms
